In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


In [2]:
df = pd.read_csv("../input/car-prices/carPrices.csv")
df

Car_Model  Mileage  Sell_Prices  Ages
0                  BMW X5    69000        18000     6
1                  BMW X5    35000        34000     3
2                  BMW X5    57000        26100     5
3                  BMW X5    22500        40000     2
4                  BMW X5    46000        31500     4
5                 Audi A5    59000        29400     5
6                 Audi A5    52000        32000     5
7                 Audi A5    72000        19300     6
8                 Audi A5    91000        12000     8
9   Mercedez Benz C class    67000        22000     6
10  Mercedez Benz C class    83000        20000     7
11  Mercedez Benz C class    79000        21000     7
12  Mercedez Benz C class    59000        33000     5

In [3]:
le = LabelEncoder()
df.Car_Model = le.fit_transform(df.Car_Model)
df

Car_Model  Mileage  Sell_Prices  Ages
0           1    69000        18000     6
1           1    35000        34000     3
2           1    57000        26100     5
3           1    22500        40000     2
4           1    46000        31500     4
5           0    59000        29400     5
6           0    52000        32000     5
7           0    72000        19300     6
8           0    91000        12000     8
9           2    67000        22000     6
10          2    83000        20000     7
11          2    79000        21000     7
12          2    59000        33000     5

In [4]:
x = df[['Car_Model', 'Mileage', 'Ages']].values
x

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [5]:
y = df.Sell_Prices
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell_Prices, dtype: int64

In [6]:
ct = ColumnTransformer([('Car_Model', OneHotEncoder(), [0])], remainder='passthrough')

In [7]:
x = ct.fit_transform(x)
x

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [8]:
x = x[:, 1:]
x

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [9]:
model = linear_model.LinearRegression()
model.fit(x, y)

LinearRegression()

In [10]:
model.predict([[0, 1, 45000, 4]])

array([36991.31721062])

In [11]:
model.predict([[1, 0, 86000, 7]])

array([11080.74313219])

In [12]:
model.score(x, y)

0.9417050937281082